--=CONCATENATE("insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('";A2;"','";C2;"',5,1.00);")
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AAPL','Apple Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BAC','Bank of America Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('WMT','Wal-Mart Stores',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('FB','Facebook Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BABA','Alibaba Group Holding Ltd',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GE','General Electric Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('NVDA','Nvidia Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MSFT','Microsoft Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AMZN','Amazon.Com Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MU','Micron Technology',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('NFLX','Netflix Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('QCOM','Qualcomm Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('C','Citigroup Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('INTC','Intel Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('JPM','JP Morgan Chase & Co',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TWTR','Twitter Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SNAP','Snap Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('WFC','Wells Fargo & Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('F','Ford Motor Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AMD','Adv Micro Devices',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('XOM','Exxon Mobil Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('HD','Home Depot',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TSLA','Tesla Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BA','Boeing Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('T','AT&T Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GM','General Motors Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CSCO','Cisco Systems Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('X','United States Steel Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('JD','Jd.Com Inc Ads',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('VZ','Verizon Communications Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('FCX','Freeport-Mcmoran Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('DVN','Devon Energy Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TEVA','Teva Pharmaceutical Industries Ltd',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('DAL','Delta Air Lines Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AMAT','Applied Materials',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GOOGL','Alphabet Class A',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GS','Goldman Sachs Group',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SQ','Square',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('DIS','Walt Disney Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MCD','McDonalds Corp',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AAL','American Airlines Gp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BIDU','Baidu Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GILD','Gilead Sciences Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CAT','Caterpillar Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('UPS','United Parcel Service',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CAR','Avis Budget Group I',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AKS','AK Steel Holding Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CVX','Chevron Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('HAL','Halliburton Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('HTZ','Hertz Global Holdings Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BMY','Bristol-Myers Squibb Company',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MRK','Merck & Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('VRX','Valeant Pharmaceuticals Intl',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('WYNN','Wynn Resorts Ltd',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('V','Visa Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('UNP','Union Pacific Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('KO','Coca-Cola Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MAR','Marriot Int Class A',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('IBM','International Business Machines',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CMG','Chipotle Mexican Grill',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('ABBV','Abbvie Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('RIG','Transocean Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MOS','Mosaic Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MA','Mastercard Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SIRI','Sirius XM Holdings I',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AZN','Astrazeneca Plc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('M','Macys Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('UAL','United Continental Holdings',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('ILG','Ilg Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SLB','Schlumberger N.V.',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GIS','General Mills',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('JNJ','Johnson & Johnson',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CVS','CVS Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('PFE','Pfizer Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('PG','Procter & Gamble Company',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AIG','American International Group',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('PANW','Palo Alto Networks Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('ORCL','Oracle Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('KGC','Kinross Gold Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TPX','Tempur-Pedic International Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('FEYE','Fireeye Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('PYPL','Paypal Holdings',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('RF','Regions Financial Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AMGN','Amgen',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('WEN','Wendys Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SBUX','Starbucks Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('ATVI','Activision Blizzard',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('APA','Apache Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('EAT','Brinker International',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('ADBE','Adobe Systems Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MS','Morgan Stanley',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('RIOT','Riot Blockchain Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('HES','Hess Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SHOP','Shopify Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('FCAU','Fiat Chrysler Automobiles N.V.',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AAP','Advance Auto Parts Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AUY','Yamana Gold',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BP','BP Plc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TRIP','Tripadvisor Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TGT','Target Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('KMI','Kinder Morgan',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CSX','CSX Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('PAAS','Pan Amer Silver Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MGM','MGM Resorts International',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AXP','American Express Company',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('BHGE','Baker Hughes A Ge Co. Cl. A',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CRM','Salesforce.Com Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('S','Sprint Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('COST','Costco Wholesale',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('OSTK','Overstock.Com Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('UTX','United Technologies Corp',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TTD','Trade Desk Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('AVGO','Broadcom Ltd',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('MO','Altria Group',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('CTL','Centurylink',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TWX','Time Warner Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('ADSK','Autodesk Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TXN','Texas Instruments',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('EBAY','Ebay Inc',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('LVS','Las Vegas Sands',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('EA','Electronic Arts Inc',5,1.00);

insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SPY','S&P 500 SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('QQQ','Nasdaq QQQ ETF',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('IWM','Russell 2000 Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('VXX','VIX Short-Term Futures ETN Ipath',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('EEM','Emrg Mkts ETF MSCI Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('XOP','S&P Oil & Gas Expl & Prod SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('TLT','20 Year Bond Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('EWZ','Brazil Index MSCI Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('EFA','EAFE Index MSCI Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('XLF','S&P 500 Financials Sector SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('HYG','Iboxx $ High Yield Corp Bond Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('UVXY','Ultra VIX Short-Term Fut Proshares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GLD','Gold SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('XLU','S&P 500 Utilities Sector SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('DIA','DOW Industrials SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('XLE','S&P 500 Energy Sector SPDR',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('USO','US Oil Fund',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SLV','Silver Trust Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('GDX','Gold Miners Vaneck ETF',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('FXI','FTSE China 25 Index Ishares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SMH','Semiconductor Vaneck ETF',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('SVXY','VIX Short-Term Fut Short Proshares',5,1.00);
insert into stocks (`ticker`,`stock_name`,`interval`,renko_box_size) values('XLI','S&P 500 Industrial Sector SPDR',5,1.00);
insert into monitored_stocks (stocknum, `interval`, added_date, added_by, trennd) select stocknum, `interval`, current_timestamp,1,1 from stocks;